CREATE TABLE review (
    id INTEGER PRIMARY KEY,
    place_id VARCHAR(32) NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    comment TEXT NOT NULL,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (place_id) REFERENCES places(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);